
export interface propsDormForm {
    DormName : string,
    DormAddress : string,
    DormLongitude : number,
    DormLatitude : number,
    phone : string,
    email : string,
    LineID : string,
    Website : string,
    DormDoc : any,
    AccomType: string,
    AllowSex: string,
    HaveConString: string,
    ConDistance: string,
    ConDescript: string, 
    HaveLaunString: string,
    LaunDistance: string,
    LaunDescript: string,
    HaveParkLotString: string,
    ParkLotDistance: string,
    ParkLotDescript: string,
    HaveRestaurantString: string,
    RestuarantDistance: string,
    RestuarantDescript: string,
    HaveSmokeAreaString: string,
    SmokeDistance: string,
    SmokeDescript: string,
    HaveFitnessString: string,
    FitnessDistance: string,
    FitnessDescript: string,
    HavePoolString: string,
    PoolDistance: string,
    PoolDescript: string,
    HaveCommonString: string,
    CommonDistance: string,
    CommonDescript: string,
    HaveInternetString: string,
    InternetDescript: string,
    HaveRestString : string,
    RestDescript : string,
    AllowedPet? : string,
    AllowedCook? : string,
    DormImage : any,
    acceptTerm : boolean,
}
export interface termService {
    show : boolean, 
    handleClose : ()=>void
}
