version: '3.7'

services:
  frontend:
    container_name: frontend-dev
    image: ghcr.io/dormlife-softeng/frontend-baseimage:0.3-dev
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
